### ISSUE TITLE
SGLD not imported in the PyTorch branch

### ISSUE THREAD

**Issue by ocrinz** [MFreidank/pysgmcmc#4]
Hi, 

https://github.com/MFreidank/pysgmcmc/blob/3500820e520c6019a36bc7e8563efc2ca0371d60/pysgmcmc/optimizers/__init__.py#L1-L7

Seems that SGLD could not be imported directly from `pysgmcmc.optimizers`, unlike SGHMC.  I guess we should add a line:

```py
from pysgmcmc.optimizers.sgld import SGLD
```

**Comment by MFreidank** [comment]
Hello there @ocrinz ,

Thanks for reporting this, I've pushed a new commit just now that resolves this.
Please note that a more mature version of my pytorch branch is maintained over at: https://github.com/automl/pybnn

**Comment by MFreidank** [comment]
Closing as resolved.
